development:
  adapter: postgresql
  database: Blogger
  username: nirmal
  password: 7139970
  encoding: unicode
  host: localhost
  pool: 5

test:
  adapter: postgresql
  database: Blogger
  username: nirmal
  password: 7139970
  encoding: unicode
  host: localhost
  pool: 5
